
version: '3.8'

networks: 
    mongo-compose-network:
      driver: bridge
volumes: 
  mongo_vol:


services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    restart: always

  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db
    networks:
      - mongo-compose-network

